---
title: "Digital Ecology"
description: |
  Using digital technologies to help ecologists and environmental scientists collect, manage, analyse and share data.
site: distill::distill_website
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

# Learn more about creating websites with Distill at:
# https://rstudio.github.io/distill/website.html

```

<!-- Fathom - simple website analytics - https://github.com/usefathom/fathom -->
<script>
(function(f, a, t, h, o, m){
	a[h]=a[h]||function(){
		(a[h].q=a[h].q||[]).push(arguments)
	};
	o=f.createElement('script'),
	m=f.getElementsByTagName('script')[0];
	o.async=1; o.src=t; o.id='fathom-script';
	m.parentNode.insertBefore(o,m)
})(document, window, '//139.59.172.171/tracker.js', 'fathom');
fathom('set', 'siteId', 'OSWPF');
fathom('trackPageview');
</script>
<!-- / Fathom -->

Digital Ecology can help you with data, software, workflows and training. We are dedicated to helping you make the best use of open source technologies to improve your data collection and dissemination, making your business more efficient and achieving better outcomes for the environment.

Digital Ecology is run by ecologists and environmental scientists with a passion for open source digital technologies. We understand your needs and have the tools to help you work smarter.

Get in touch today to find out how we can help you.
